<?php
$_helper = Mage::helper('proxiblue_exacttarget');
?>
<?php if (!$this->hasAlreadyTracked() && $_helper->isEnabled() && $this->isEnabled()): ?>
    <!-- EXACTTARGET TRACKING SCRIPT - MODULE BY PROXIBLUE.COM.AU -->
    <script type="text/javascript" src="<?php echo $_helper->getConnectUrl(); ?>"></script>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            if (typeof(_etmc) !== "undefined") {
                _etmc.push(["setOrgId", "<?php echo $_helper->getAccountId(); ?>"]);
                _etmc.push(["<?php echo $this->getTrackType(); ?>"
                    <?php if ($_trackData = $this->getTrackData()):?>, {
                        "cart": <?php echo $_trackData; ?>,
                        "order_number": "<?php echo $this->getIncrementId(); ?>",
                        "discount": "<?php echo $this->getDiscountAmount(); ?>",
                        "shipping": "<?php echo $this->getShippingDescription(); ?>"
                    }
                    <?php endif; ?>]);
                _etmc.push(["trackEvent", {
                    "name": "Payment Method",
                    "details": {
                        "order_number": "<?php echo $this->getIncrementId(); ?>",
                        "payment_method": "<?php echo $this->getPaymentMethod(); ?>",
                    }
                }
                ]);
            }
        });
    </script>
    <!-- END EXACTTARGET TRACKING -->
    <?php $this->flagHasTracked(); ?>
<?php endif; ?>
